# Generated by Django 5.2.7 on 2026-05-06 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("gemini", "Gemini"),
                            ("morpheus", "Morpheus (TUM CIT)"),
                            ("custom", "Custom API (OpenAI-compatible)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="User-friendly name (e.g. 'My Work OpenAI')",
                        max_length=100,
                    ),
                ),
                (
                    "encrypted_key",
                    models.BinaryField(help_text="Fernet-encrypted API key bytes"),
                ),
                (
                    "key_fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="HMAC-SHA256 fingerprint of raw key (for duplicate detection)",
                        max_length=64,
                    ),
                ),
                (
                    "masked_key",
                    models.CharField(
                        help_text="Pre-computed masked display key (e.g. '••••abcd')",
                        max_length=20,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Custom API base URL — e.g. https://api.openai.com/v1 (NOT the completions endpoint)",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User API Key",
                "verbose_name_plural": "User API Keys",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="user_api_keys_active_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "label"), name="unique_user_key_label"
                    )
                ],
            },
        ),
    ]
