# Generated by Django 5.2.7 on 2026-05-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapikey",
            name="base_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Custom API base URL — e.g. https://api.openai.com/v1 (NOT the completions endpoint)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="userapikey",
            name="disabled_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reason the key was disabled. 'auth_failure' means the provider rejected the key; user must re-enter a valid key to re-enable.",
                max_length=50,
            ),
        ),
    ]
