# Generated by Django 5.2 on 2025-08-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiservicetoken",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("huggingface", "Hugging Face"),
                    ("github", "GitHub Models"),
                    ("google", "Google Gemini"),
                ],
                max_length=20,
            ),
        ),
    ]
