# Generated by Django 5.2.7 on 2026-05-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usersalt"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapikey",
            name="disabled_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reason the key was disabled. 'auth_failure' means the provider rejected the key; user must re-enter a valid key to re-enable.",
                max_length=50,
            ),
        ),
    ]
