"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import hashlib
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add the project root to Python path
PROJECT_ROOT = BASE_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")

# Load environment variables from .env file
load_dotenv(BASE_DIR.parent / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-wxqcjs8ufub1x#x)nwi-y4k+sv@$r@9-=&dp!8r=sp8ee=#lh%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS: list = ["pixie.soc.cit.tum.de", "localhost", "127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "pxnodes",
    "llm",
    "pillars",
    "accounts",
    "pxcharts",
    "player_expectations",
    "moviescriptevaluator",
    "player_expectations_new",
    "game_concept",
    "sparc",
]

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "100/minute",
        "api_key_test": "10/minute",
    },
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://localhost",
]

CORS_ALLOW_CREDENTIALS = True

# Session settings
# Note: Django has two independent session lifetimes:
#   1. SESSION_COOKIE_AGE  — server-side session record expiry (24 h).
#   2. SESSION_EXPIRE_AT_BROWSER_CLOSE — cookie lifetime (session cookie).
# They apply simultaneously: the session record is cleaned after 24 h
# regardless of browser state, AND the cookie is discarded on browser close.
# The encryption key inside the session has its own 1-hour TTL tracked
# independently — see accounts/encryption.py KEY_TTL_SECONDS.
SESSION_COOKIE_AGE = 86400  # 24 hours — server-side session record TTL
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG  # False in dev (HTTP), True in production (HTTPS)
# ⚠️  WARNING: Never unconditionally set this to False in production.
#    A staging or review environment might run with DEBUG=False over HTTP
#    (e.g. behind a reverse proxy that terminates TLS). In that case,
#    SESSION_COOKIE_SECURE must be True regardless of DEBUG.
#    See also SECURE_PROXY_SSL_HEADER below.
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = not DEBUG  # False in dev (HTTP), True in production (HTTPS)

# Trust Caddy proxy for HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

ROOT_URLCONF = "api.urls"

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://localhost",
    "https://pixie.soc.cit.tum.de",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation"
        ".UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# === API Key Encryption ===
# Keys are encrypted with a Fernet key derived from the user's login password
# and stored ONLY in the server-side session. No global encryption key needed.
# See accounts/encryption.py for the derivation mechanism.

# Pepper for HMAC-based key fingerprinting (prevents oracle attacks on key_hash).
# Set this to a random string in production. If empty, key fingerprinting is weaker.
API_KEY_FINGERPRINT_PEPPER = os.getenv(
    "API_KEY_FINGERPRINT_PEPPER",
    hashlib.sha256(f"{SECRET_KEY}:fingerprint".encode()).hexdigest() if DEBUG else "",
)

if not API_KEY_FINGERPRINT_PEPPER and not DEBUG:
    raise RuntimeError(
        "API_KEY_FINGERPRINT_PEPPER is not set. "
        "This is required in production — key fingerprinting with an empty pepper "
        "makes HMAC-based duplicate detection trivially bypassable. "
        "Set a random string via the API_KEY_FINGERPRINT_PEPPER env variable."
    )
