# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and lock files in the `frontend` directory
    directory: "/frontend"
    schedule:
      interval: "weekly"
    target-branch: "dependabot"

  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `requirements.txt` or `pyproject.toml` in the `backend` directory
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "dependabot"

