# Generated by Django 5.2.7 on 2026-05-09 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Project",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "name",
                            models.CharField(blank=True, default="", max_length=255),
                        ),
                        ("description", models.TextField(blank=True, default="")),
                        (
                            "is_current",
                            models.BooleanField(
                                default=False,
                                help_text="Whether this is the user's current project",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="projects",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "game_concept_project",
                        "ordering": ["-updated_at"],
                        "constraints": [
                            models.UniqueConstraint(
                                condition=models.Q(("is_current", True)),
                                fields=("user",),
                                name="one_current_project_per_user",
                            )
                        ],
                    },
                )
            ],
        )
    ]
