# Generated by Django 5.2.7 on 2026-05-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="project",
            table="projects_project",
        ),
    ]
