# Generated by Django 5.2.7 on 2026-05-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="genres",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="target_platform",
            field=models.CharField(
                choices=[
                    ("web", "Web"),
                    ("mobile", "Mobile"),
                    ("desktop", "Desktop"),
                    ("console", "Console"),
                ],
                default="desktop",
                max_length=20,
            ),
        ),
    ]
