# Generated by Django 5.2.7 on 2026-05-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_genres_project_target_platform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="target_platform",
        ),
        migrations.AddField(
            model_name="project",
            name="target_platforms",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
