# Generated by Django 5.2.7 on 2026-02-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReviewLocator",
            fields=[
                (
                    "recommendation_id",
                    models.TextField(primary_key=True, serialize=False),
                ),
                ("raw_json", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("updated_at", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "review_locator",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QuoteCodeSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_id", models.IntegerField()),
                ("code_int", models.IntegerField()),
                ("coarse_category", models.TextField()),
                ("sentiment", models.TextField(blank=True, null=True)),
                ("raw_specialist_json", models.TextField(blank=True, null=True)),
                ("raw_sentiment_json", models.TextField(blank=True, null=True)),
                ("updated_at", models.IntegerField(blank=True, null=True)),
                ("sentiment_v2", models.TextField(blank=True, null=True)),
                ("raw_sentiment_v2_json", models.TextField(blank=True, null=True)),
                ("updated_at_v2", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "quote_code_sentiment",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["coarse_category", "code_int"],
                        name="idx_qcs_coarse_code",
                    )
                ],
                "unique_together": {("quote_id", "coarse_category", "code_int")},
            },
        ),
        migrations.CreateModel(
            name="ReviewQuotes",
            fields=[
                ("quote_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "recommendation_id",
                    models.TextField(blank=True, db_index=True, null=True),
                ),
                ("app_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("game_name", models.TextField(blank=True, null=True)),
                ("coarse_category", models.TextField(blank=True, null=True)),
                ("quote_text", models.TextField(blank=True, null=True)),
                ("created_at", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "review_quotes",
                "managed": True,
                "indexes": [
                    models.Index(fields=["recommendation_id"], name="idx_rq_rec_id"),
                    models.Index(fields=["app_id"], name="idx_rq_app_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ThesisDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_id", models.TextField(db_index=True)),
                ("app_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("language", models.TextField(blank=True, null=True)),
                ("review_text", models.TextField(blank=True, null=True)),
                (
                    "timestamp_created",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("voted_up", models.IntegerField(blank=True, db_index=True, null=True)),
                ("votes_up", models.IntegerField(blank=True, null=True)),
                ("weighted_vote_score", models.TextField(blank=True, null=True)),
                ("review_text_en", models.TextField(blank=True, null=True)),
                ("votes_funny", models.IntegerField(blank=True, null=True)),
                (
                    "written_during_early_access",
                    models.IntegerField(blank=True, null=True),
                ),
                ("received_for_free", models.IntegerField(blank=True, null=True)),
                ("num_reviews", models.IntegerField(blank=True, null=True)),
                ("playtime_forever", models.IntegerField(blank=True, null=True)),
                ("playtime_at_review", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "thesis_dataset",
                "managed": True,
                "indexes": [
                    models.Index(fields=["recommendation_id"], name="idx_td_rec_id"),
                    models.Index(fields=["app_id"], name="idx_td_app_id"),
                    models.Index(
                        fields=["timestamp_created"], name="idx_td_ts_created"
                    ),
                    models.Index(fields=["voted_up"], name="idx_td_voted_up"),
                ],
            },
        ),
    ]
