services:
  caddy:
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile

  ################################################################################################
  #                                     LOCAL configuration                                      #
  ################################################################################################
  backend-dev:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        DJANGO_PORT: $DJANGO_PORT_DEV
        SQLITE_DB_PATH: /app/data/db.sqlite3
    ports:
      - "8000:${DJANGO_PORT_DEV:-8000}"
    volumes:
      - ../backend:/backend
    command: >
      sh -c "python manage.py migrate --noinput &&
      uvicorn api.asgi:application --host 0.0.0.0 --port $${DJANGO_PORT:-8000} --reload"

  frontend-dev:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ../frontend:/app
      - frontend-node-modules:/app/node_modules
      - frontend-nuxt-cache:/app/.nuxt
      - ../package.json:/package.json
      - ../.git:/app/.git
    environment:
      - NUXT_HOST=0.0.0.0
      - HOST=0.0.0.0
      - NITRO_HOST=0.0.0.0
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    extra_hosts:
      - "localhost:host-gateway"

volumes:
  frontend-node-modules:
  frontend-nuxt-cache:
