# Generated by Django 5.2 on 2025-07-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxnodes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pxcomponent",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pxcomponentdefinition",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pxnode",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
