# Generated by Django 5.2 on 2025-07-05 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxnodes", "0002_pxcomponentdefinition_pxcomponent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pxcomponent",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pxcomponent",
            unique_together={("owner", "id")},
        ),
        migrations.AlterUniqueTogether(
            name="pxcomponentdefinition",
            unique_together={("owner", "id")},
        ),
        migrations.AlterUniqueTogether(
            name="pxnode",
            unique_together={("owner", "id")},
        ),
    ]
