# Generated by Django 5.2.7 on 2025-12-13 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0008_pxchart_associatednode"),
        (
            "pxnodes",
            "0004_alter_pxcomponent_id_alter_pxcomponentdefinition_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StructuralMemoryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_hash", models.CharField(max_length=64)),
                ("processed_at", models.DateTimeField(auto_now=True)),
                ("triples_count", models.IntegerField(default=0)),
                ("facts_count", models.IntegerField(default=0)),
                ("embeddings_count", models.IntegerField(default=0)),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structural_memory_states",
                        to="pxcharts.pxchart",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structural_memory_states",
                        to="pxnodes.pxnode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["node", "chart"], name="pxnodes_str_node_id_ec9e0c_idx"
                    ),
                    models.Index(
                        fields=["content_hash"], name="pxnodes_str_content_7af842_idx"
                    ),
                ],
                "unique_together": {("node", "chart")},
            },
        ),
    ]
