# Generated by Django 5.2.7 on 2026-03-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxnodes", "0005_pxkeydefinition_pxkeyassignment_pxlockdefinition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pxlockdefinition",
            name="unlock_mode",
            field=models.CharField(
                choices=[
                    ("permanent", "Permanent"),
                    ("temporary", "Temporary"),
                    ("reversible", "Reversible"),
                    ("collapsible", "Collapsible"),
                ],
                max_length=20,
            ),
        ),
    ]
