# Generated by Django 5.2.7 on 2025-12-13 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0008_pxchart_associatednode"),
        ("pxnodes", "0005_add_structural_memory_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="HMEMLayerEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "positional_index",
                    models.CharField(
                        db_index=True,
                        help_text="Format: L{layer}.{project}.{chart}.{path}.{node}",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "layer",
                    models.IntegerField(
                        choices=[
                            (1, "L1 - Domain (Project)"),
                            (2, "L2 - Category (Chart)"),
                            (3, "L3 - Trace (Path)"),
                            (4, "L4 - Episode (Node)"),
                        ],
                        db_index=True,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "embedding",
                    models.JSONField(
                        help_text="Vector embedding as JSON array of floats"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(default="text-embedding-3-small", max_length=100),
                ),
                ("embedding_dim", models.IntegerField(default=1536)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hmem_embeddings",
                        to="pxcharts.pxchart",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hmem_embeddings",
                        to="pxnodes.pxnode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["layer", "chart"], name="pxnodes_hme_layer_104e5c_idx"
                    ),
                    models.Index(
                        fields=["layer", "node"], name="pxnodes_hme_layer_28dd4f_idx"
                    ),
                    models.Index(
                        fields=["positional_index"],
                        name="pxnodes_hme_positio_b7c659_idx",
                    ),
                    models.Index(
                        fields=["content_hash"], name="pxnodes_hme_content_e6a04b_idx"
                    ),
                ],
            },
        ),
    ]
