# Generated by Django 5.2.7 on 2026-04-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxnodes", "0006_alter_pxlockdefinition_unlock_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="pxlockdefinition",
            name="soft_gate",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
