# Generated by Django 5.2.7 on 2025-12-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0008_pxchart_associatednode"),
        ("pxnodes", "0006_add_hmem_layer_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmemlayerembedding",
            name="child_indices",
            field=models.JSONField(
                default=list,
                help_text="List of positional indices of child entries (for hierarchical routing)",
            ),
        ),
        migrations.AddField(
            model_name="hmemlayerembedding",
            name="parent_index",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Positional index of parent entry (for hierarchical routing)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="hmemlayerembedding",
            index=models.Index(
                fields=["parent_index"], name="pxnodes_hme_parent__610daf_idx"
            ),
        ),
    ]
