# Generated by Django 5.2.7 on 2025-12-22 18:10

import django.db.models.deletion
from django.db import migrations, models


def backfill_project(apps, schema_editor):
    User = apps.get_model("auth", "User")
    GameConcept = apps.get_model("game_concept", "GameConcept")
    PxNode = apps.get_model("pxnodes", "PxNode")
    PxComponentDefinition = apps.get_model("pxnodes", "PxComponentDefinition")

    for user in User.objects.all():
        project = GameConcept.objects.filter(user=user, is_current=True).first()
        if not project:
            continue
        PxNode.objects.filter(owner=user, project__isnull=True).update(project=project)
        PxComponentDefinition.objects.filter(owner=user, project__isnull=True).update(
            project=project
        )


class Migration(migrations.Migration):

    dependencies = [
        ("game_concept", "0001_initial"),
        ("pxnodes", "0007_add_hmem_routing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="pxcomponentdefinition",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pxcomponentdefinitions",
                to="game_concept.gameconcept",
            ),
        ),
        migrations.AddField(
            model_name="pxnode",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pxnodes",
                to="game_concept.gameconcept",
            ),
        ),
        migrations.RunPython(backfill_project, migrations.RunPython.noop),
    ]
