# Generated by Django 5.2.7 on 2026-05-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pxnodes", "0007_pxlockdefinition_soft_gate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pxkeydefinition",
            old_name="type",
            new_name="key_type",
        ),
    ]
