# Generated by Django 5.2.7 on 2025-12-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxnodes", "0008_pxcomponentdefinition_project_pxnode_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuralmemorystate",
            name="summary_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="structuralmemorystate",
            name="trace_summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
