# Generated by Django 5.2.7 on 2026-04-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pxnodes", "0011_pxnode_project_fk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="artifactembedding",
            new_name="pxnodes_art_artifac_56e8c1_idx",
            old_name="pxnodes_art_artifac_7f6c8f_idx",
        ),
        migrations.RenameIndex(
            model_name="artifactembedding",
            new_name="pxnodes_art_embeddi_2a139d_idx",
            old_name="pxnodes_art_embedding_9d5395_idx",
        ),
        migrations.RenameIndex(
            model_name="contextartifact",
            new_name="pxnodes_con_scope_t_14f1a1_idx",
            old_name="pxnodes_con_scope_t_a7a08e_idx",
        ),
        migrations.RenameIndex(
            model_name="contextartifact",
            new_name="pxnodes_con_chart_i_b074dd_idx",
            old_name="pxnodes_con_chart_i_69c6a6_idx",
        ),
        migrations.RenameIndex(
            model_name="contextartifact",
            new_name="pxnodes_con_node_id_29e847_idx",
            old_name="pxnodes_con_node_id_8b22ea_idx",
        ),
    ]
