# Generated by Django 5.2.7 on 2026-05-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "__first__"),
        (
            "pxnodes",
            "0012_rename_pxnodes_art_artifac_7f6c8f_idx_pxnodes_art_artifac_56e8c1_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pxcomponentdefinition",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pxcomponentdefinitions",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="pxnode",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pxnodes",
                to="projects.project",
            ),
        ),
    ]
