# Generated by Django 5.2.7 on 2026-05-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_auto_20260510_1642"),
        ("pxnodes", "0014_alter_pxcomponentdefinition_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pxcomponentdefinition",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pxcomponentdefinitions",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="pxnode",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pxnodes",
                to="projects.project",
            ),
        ),
    ]
