# Generated by Django 5.2.7 on 2026-05-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pxnodes", "0008_rename_type_pxkeydefinition_key_type"),
        ("pxnodes", "0015_alter_pxcomponentdefinition_project_and_more"),
    ]

    operations = []
