# Generated by Django 5.2.15 on 2026-06-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxnodes", "0016_merge_20260513_1426"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pxkeydefinition",
            name="key_type",
            field=models.CharField(
                choices=[("item", "Item"), ("ability", "Ability"), ("other", "Other")],
                max_length=20,
            ),
        ),
    ]
