# Generated by Django 5.2.15 on 2026-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pxnodes",
            "0018_alter_pxcomponent_id_alter_pxcomponentdefinition_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pxkeydefinition",
            name="symbol",
            field=models.CharField(default="🔑", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pxlockdefinition",
            name="symbol",
            field=models.CharField(default="🔒", max_length=20),
            preserve_default=False,
        ),
    ]
