# Generated by Django 5.2.7 on 2026-03-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_concept", "0002_project_model_and_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameconcept",
            name="is_current",
            field=models.BooleanField(
                default=True,
                help_text="Whether this is the project's current game concept",
            ),
        ),
    ]
