# Generated by Django 5.2.7 on 2026-05-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_concept", "0003_alter_gameconcept_is_current"),
        ("projects", "__first__"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameconcept",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_concepts",
                to="projects.project",
            ),
        ),
    ]
