# Generated by Django 5.2.7 on 2026-05-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_concept", "0004_remove_project_user_alter_gameconcept_project"),
        ("pillars", "0013_alter_pillar_project"),
        ("pxcharts", "0011_alter_pxchart_project"),
        ("pxnodes", "0013_alter_pxcomponentdefinition_project_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="Project",
                ),
            ],
        ),
    ]
