# Generated by Django 5.2.7 on 2025-10-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moviescriptevaluator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetmetadata",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="assetmetadata",
            name="project_name",
        ),
    ]
