# Generated by Django 5.2.7 on 2025-10-27 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviescriptevaluator", "0002_remove_assetmetadata_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assetmetadata",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets_metadata",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assetmetadata",
            name="project_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
