# Generated by Django 5.2.7 on 2025-11-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "moviescriptevaluator",
            "0004_moviescript_remove_assetmetadata_owner_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieproject",
            old_name="project_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="movieproject",
            old_name="project_name",
            new_name="name",
        ),
    ]
