# Generated by Django 5.2.7 on 2025-12-15 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "moviescriptevaluator",
            "0005_rename_project_description_movieproject_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moviescript",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moviescript",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scripts",
                to="moviescriptevaluator.movieproject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moviescript",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
