# Generated by Django 5.2.7 on 2026-01-04 12:06

import moviescriptevaluator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "moviescriptevaluator",
            "0006_moviescript_created_at_moviescript_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviescript",
            name="file",
            field=models.FileField(
                upload_to=moviescriptevaluator.models.upload_to_scripts
            ),
        ),
    ]
