# Generated by Django 5.2.7 on 2026-01-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviescriptevaluator", "0007_alter_moviescript_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="requiredassets",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_assets",
                to="moviescriptevaluator.assetmetadata",
            ),
        ),
        migrations.CreateModel(
            name="ScriptSceneAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="moviescriptevaluator.movieproject",
                    ),
                ),
            ],
        ),
    ]
