# Generated by Django 5.2.7 on 2026-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviescriptevaluator", "0008_requiredassets_asset_scriptsceneanalysisresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptsceneanalysisresult",
            name="asset_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scriptsceneanalysisresult",
            name="asset_type",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scriptsceneanalysisresult",
            name="fab_search_keyword",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scriptsceneanalysisresult",
            name="notes",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scriptsceneanalysisresult",
            name="scene",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
