# Generated by Django 5.2.7 on 2026-01-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviescriptevaluator", "0009_scriptsceneanalysisresult_asset_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scriptsceneanalysisresult",
            name="asset_coverage",
            field=models.CharField(
                choices=[
                    ("NOT_ANALYZED", "Not Analyzed"),
                    ("FOUND", "Found"),
                    ("NOT_FOUND", "Not Found"),
                ],
                default="NOT_ANALYZED",
                max_length=20,
            ),
        ),
    ]
