# Generated by Django 5.2.7 on 2025-10-30 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SPARCEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_text",
                    models.TextField(help_text="The game concept text being evaluated"),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional context or constraints",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("monolithic", "Monolithic"),
                            ("quick_scan", "Quick Scan (Agentic)"),
                            ("deep_dive", "Deep Dive (Agentic)"),
                            ("interactive", "Interactive (Agentic)"),
                        ],
                        help_text="Execution mode used for evaluation",
                        max_length=20,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="LLM model used for evaluation", max_length=100
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        help_text="Total execution time in milliseconds"
                    ),
                ),
                (
                    "total_tokens",
                    models.IntegerField(
                        default=0, help_text="Total tokens used (prompt + completion)"
                    ),
                ),
                (
                    "estimated_cost_eur",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="Estimated cost in EUR",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SPARC Evaluation",
                "verbose_name_plural": "SPARC Evaluations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SPARCEvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("player_experience", "Player Experience"),
                            ("theme", "Theme"),
                            ("gameplay", "Gameplay"),
                            ("place", "Place"),
                            ("unique_features", "Unique Features"),
                            ("story_narrative", "Story & Narrative"),
                            ("goals_challenges_rewards", "Goals, Challenges & Rewards"),
                            ("art_direction", "Art Direction"),
                            ("purpose", "Purpose"),
                            ("opportunities_risks", "Opportunities & Risks"),
                        ],
                        help_text="Which SPARC aspect this result covers",
                        max_length=50,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        help_text="Completeness score (0-100) for this aspect",
                        null=True,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of agent that produced this result (for agentic mode)",
                        max_length=100,
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Model used for this specific aspect",
                        max_length=100,
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution time for this aspect in ms",
                        null=True,
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        help_text="Full evaluation result as JSON (structured output from LLM)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluation",
                    models.ForeignKey(
                        help_text="The parent evaluation session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspect_results",
                        to="sparc.sparcevaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "SPARC Aspect Result",
                "verbose_name_plural": "SPARC Aspect Results",
                "ordering": ["aspect"],
            },
        ),
    ]
