# Generated by Django 5.2.7 on 2025-11-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparcevaluationresult",
            name="aspect",
            field=models.CharField(
                choices=[
                    ("player_experience", "Player Experience"),
                    ("theme", "Theme"),
                    ("gameplay", "Gameplay"),
                    ("place", "Place"),
                    ("unique_features", "Unique Features"),
                    ("story_narrative", "Story & Narrative"),
                    ("goals_challenges_rewards", "Goals, Challenges & Rewards"),
                    ("art_direction", "Art Direction"),
                    ("purpose", "Purpose"),
                    ("opportunities_risks", "Opportunities & Risks"),
                    ("aggregated", "Aggregated Results"),
                ],
                help_text="Which SPARC aspect this result covers",
                max_length=50,
            ),
        ),
    ]
