# Generated by Django 5.2.7 on 2025-11-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparc", "0002_alter_sparcevaluationresult_aspect"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparcevaluationresult",
            name="completion_tokens",
            field=models.IntegerField(
                default=0, help_text="Number of completion/output tokens used"
            ),
        ),
        migrations.AddField(
            model_name="sparcevaluationresult",
            name="estimated_cost_eur",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="Estimated cost in EUR for this aspect",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sparcevaluationresult",
            name="prompt_tokens",
            field=models.IntegerField(
                default=0, help_text="Number of prompt/input tokens used"
            ),
        ),
        migrations.AddField(
            model_name="sparcevaluationresult",
            name="total_tokens",
            field=models.IntegerField(
                default=0, help_text="Total tokens used (prompt + completion)"
            ),
        ),
    ]
