# Generated by Django 5.2.7 on 2025-11-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparc", "0003_sparcevaluationresult_completion_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparcevaluationresult",
            name="input_data",
            field=models.JSONField(
                blank=True, help_text="Input data sent to the agent as JSON", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sparcevaluation",
            name="mode",
            field=models.CharField(
                choices=[
                    ("monolithic", "Monolithic"),
                    ("quick_scan", "Quick Scan (Agentic)"),
                    ("deep_dive", "Deep Dive (Agentic)"),
                    ("interactive", "Interactive (Agentic)"),
                    ("router_v2", "Router V2 (Full)"),
                    ("router_v2_single", "Router V2 (Single Aspect)"),
                    ("router_v2_multiple", "Router V2 (Multiple Aspects)"),
                ],
                help_text="Execution mode used for evaluation",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="sparcevaluationresult",
            name="aspect",
            field=models.CharField(
                choices=[
                    ("player_experience", "Player Experience"),
                    ("theme", "Theme"),
                    ("gameplay", "Gameplay"),
                    ("place", "Place"),
                    ("unique_features", "Unique Features"),
                    ("story_narrative", "Story & Narrative"),
                    ("goals_challenges_rewards", "Goals, Challenges & Rewards"),
                    ("art_direction", "Art Direction"),
                    ("purpose", "Purpose"),
                    ("opportunities_risks", "Opportunities & Risks"),
                    ("aggregated", "Aggregated Results"),
                    ("router", "Router (V2)"),
                    ("synthesis", "Synthesis (V2)"),
                ],
                help_text="Which SPARC aspect this result covers",
                max_length=50,
            ),
        ),
    ]
