# Generated by Django 5.2.7 on 2025-11-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sparc", "0004_sparcevaluationresult_input_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparcevaluation",
            name="pillar_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "All Pillars"),
                    ("filtered", "Filtered Pillars"),
                    ("none", "No Pillar Integration"),
                ],
                help_text="Pillar integration mode (V2 only)",
                max_length=20,
                null=True,
            ),
        ),
    ]
