# Generated by Django 5.2.7 on 2025-11-25 15:20

from django.db import migrations, models


def rename_filtered_to_smart(apps, schema_editor):
    """Update existing 'filtered' values to 'smart' in the database."""
    SPARCEvaluation = apps.get_model("sparc", "SPARCEvaluation")
    SPARCEvaluation.objects.filter(pillar_mode="filtered").update(pillar_mode="smart")


def reverse_rename(apps, schema_editor):
    """Reverse migration: change 'smart' back to 'filtered'."""
    SPARCEvaluation = apps.get_model("sparc", "SPARCEvaluation")
    SPARCEvaluation.objects.filter(pillar_mode="smart").update(pillar_mode="filtered")


class Migration(migrations.Migration):

    dependencies = [
        ("sparc", "0005_sparcevaluation_pillar_mode"),
    ]

    operations = [
        # First, migrate the data
        migrations.RunPython(rename_filtered_to_smart, reverse_rename),
        # Then, alter the field definition
        migrations.AlterField(
            model_name="sparcevaluation",
            name="pillar_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("all", "All Pillars"),
                    ("smart", "Smart Pillars"),
                    ("none", "No Pillar Integration"),
                ],
                help_text="Pillar integration mode (V2 only)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sparcevaluationresult",
            name="aspect",
            field=models.CharField(
                choices=[
                    ("player_experience", "Player Experience"),
                    ("theme", "Theme"),
                    ("gameplay", "Gameplay"),
                    ("place", "Place"),
                    ("unique_features", "Unique Features"),
                    ("story_narrative", "Story & Narrative"),
                    ("goals_challenges_rewards", "Goals, Challenges & Rewards"),
                    ("art_direction", "Art Direction"),
                    ("purpose", "Purpose"),
                    ("opportunities_risks", "Opportunities & Risks"),
                    ("aggregated", "Aggregated Results"),
                    ("router", "Router (V2)"),
                    ("synthesis", "Synthesis (V2)"),
                    ("pillar_context", "Pillar Context (V2)"),
                ],
                help_text="Which SPARC aspect this result covers",
                max_length=50,
            ),
        ),
    ]
