# Generated by Django 5.2 on 2025-06-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('llm', '0003_rename_title_pillar_name')]

    dependencies = [
        ("pillars", "0002_alter_pillar_unique_together_remove_pillar_pillar_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pillar",
            old_name="title",
            new_name="name",
        ),
    ]
