# Generated by Django 5.2 on 2025-07-14 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('llm', '0004_alter_gamedesigndescription_user')]

    dependencies = [
        ("pillars", "0003_rename_title_pillar_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamedesigndescription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="game_designs",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
