# Generated by Django 5.2 on 2025-10-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pillars", "0004_alter_gamedesigndescription_user"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE llm_pillar RENAME TO pillars_pillar;",
            reverse_sql="ALTER TABLE pillars_pillar RENAME TO llm_pillar;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE llm_gamedesigndescription RENAME TO pillars_gamedesigndescription;",
            reverse_sql="ALTER TABLE pillars_gamedesigndescription RENAME TO llm_gamedesigndescription;",
        ),
    ]
