# Generated by Django 5.2 on 2025-10-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pillars", "0004_alter_gamedesigndescription_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="Pillar",
            table="pillars_pillar",
        ),
        migrations.AlterModelTable(
            name="GameDesignDescription",
            table="pillars_gamedesigndescription",
        ),
    ]
