# Generated by Django 5.2.7 on 2025-11-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pillars", "0005_rename_tables_from_llm_to_pillars"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameDesignDescription",
        ),
    ]
