# Generated by Django 5.2.7 on 2025-11-22 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pillars", "0006_remove_gamedesigndescription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PillarLLMCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("validate", "Validate Pillar"),
                            ("improve", "Improve Pillar"),
                            ("improve_explained", "Improve with Explanation"),
                            ("evaluate_completeness", "Evaluate Completeness"),
                            ("evaluate_contradictions", "Evaluate Contradictions"),
                            ("suggest_additions", "Suggest Additions"),
                            ("evaluate_context", "Evaluate Context"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_id", models.CharField(max_length=100)),
                ("execution_time_ms", models.IntegerField()),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "estimated_cost_eur",
                    models.DecimalField(decimal_places=8, default=0, max_digits=10),
                ),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pillar",
                    models.ForeignKey(
                        blank=True,
                        help_text="The pillar this call relates to (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to="pillars.pillar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillar_llm_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pillar LLM Call",
                "verbose_name_plural": "Pillar LLM Calls",
                "ordering": ["-created_at"],
            },
        ),
    ]
