# Generated by Django 5.2.7 on 2025-11-23 18:50

import django.db.models.deletion
from django.db import migrations, models


def _column_exists(connection, table_name: str, column_name: str) -> bool:
    """Check if a column already exists on the table."""
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table_name)
    return any(col.name == column_name for col in description)


def add_input_data_field(apps, schema_editor):
    PillarLLMCall = apps.get_model("pillars", "PillarLLMCall")
    table_name = PillarLLMCall._meta.db_table

    if _column_exists(schema_editor.connection, table_name, "input_data"):
        return

    field = models.JSONField(
        null=True,
        blank=True,
        help_text="Input data sent to the LLM",
    )
    field.set_attributes_from_name("input_data")
    schema_editor.add_field(PillarLLMCall, field)


def remove_input_data_field(apps, schema_editor):
    PillarLLMCall = apps.get_model("pillars", "PillarLLMCall")
    table_name = PillarLLMCall._meta.db_table

    if not _column_exists(schema_editor.connection, table_name, "input_data"):
        return

    field = PillarLLMCall._meta.get_field("input_data")
    schema_editor.remove_field(PillarLLMCall, field)


def add_parent_call_field(apps, schema_editor):
    PillarLLMCall = apps.get_model("pillars", "PillarLLMCall")
    table_name = PillarLLMCall._meta.db_table

    if _column_exists(schema_editor.connection, table_name, "parent_call_id"):
        return

    field = models.ForeignKey(
        "pillars.PillarLLMCall",
        on_delete=django.db.models.deletion.CASCADE,
        null=True,
        blank=True,
        related_name="agent_calls",
        help_text="Parent aggregated call (for agent sub-calls)",
    )
    field.set_attributes_from_name("parent_call")
    schema_editor.add_field(PillarLLMCall, field)


def remove_parent_call_field(apps, schema_editor):
    PillarLLMCall = apps.get_model("pillars", "PillarLLMCall")
    table_name = PillarLLMCall._meta.db_table

    if not _column_exists(schema_editor.connection, table_name, "parent_call_id"):
        return

    field = PillarLLMCall._meta.get_field("parent_call")
    schema_editor.remove_field(PillarLLMCall, field)


class Migration(migrations.Migration):

    dependencies = [
        ("pillars", "0007_add_pillar_llm_call"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_input_data_field,
                    remove_input_data_field,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="pillarllmcall",
                    name="input_data",
                    field=models.JSONField(
                        blank=True, help_text="Input data sent to the LLM", null=True
                    ),
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_parent_call_field,
                    remove_parent_call_field,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="pillarllmcall",
                    name="parent_call",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Parent aggregated call (for agent sub-calls)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_calls",
                        to="pillars.pillarllmcall",
                    ),
                )
            ],
        ),
        migrations.AlterField(
            model_name="pillarllmcall",
            name="operation",
            field=models.CharField(
                choices=[
                    ("validate", "Validate Pillar"),
                    ("improve", "Improve Pillar"),
                    ("improve_explained", "Improve with Explanation"),
                    ("evaluate_completeness", "Evaluate Completeness"),
                    ("evaluate_contradictions", "Evaluate Contradictions"),
                    ("suggest_additions", "Suggest Additions"),
                    ("evaluate_context", "Evaluate Context"),
                    ("evaluate_all", "Evaluate All (Aggregated)"),
                    ("concept_fit", "Concept Fit Agent"),
                    ("contradictions", "Contradictions Agent"),
                    ("suggest_additions_agent", "Suggest Additions Agent"),
                    ("contradiction_resolution", "Contradiction Resolution Agent"),
                    ("resolve_contradictions", "Resolve Contradictions"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pillarllmcall",
            name="result_data",
            field=models.JSONField(
                blank=True, help_text="Output data returned by the LLM", null=True
            ),
        ),
    ]
