# Generated by Django 5.2.7 on 2025-11-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pillars", "0007_add_pillar_llm_call"),
    ]

    operations = [
        migrations.AddField(
            model_name="pillarllmcall",
            name="input_data",
            field=models.JSONField(
                blank=True, help_text="Input data sent to the LLM", null=True
            ),
        ),
        migrations.AddField(
            model_name="pillarllmcall",
            name="parent_call",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent aggregated call (for agent sub-calls)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_calls",
                to="pillars.pillarllmcall",
            ),
        ),
        migrations.AlterField(
            model_name="pillarllmcall",
            name="operation",
            field=models.CharField(
                choices=[
                    ("validate", "Validate Pillar"),
                    ("improve", "Improve Pillar"),
                    ("improve_explained", "Improve with Explanation"),
                    ("evaluate_completeness", "Evaluate Completeness"),
                    ("evaluate_contradictions", "Evaluate Contradictions"),
                    ("suggest_additions", "Suggest Additions"),
                    ("evaluate_context", "Evaluate Context"),
                    ("evaluate_all", "Evaluate All (Aggregated)"),
                    ("concept_fit", "Concept Fit Agent"),
                    ("contradictions", "Contradictions Agent"),
                    ("suggest_additions_agent", "Suggest Additions Agent"),
                    ("contradiction_resolution", "Contradiction Resolution Agent"),
                    ("resolve_contradictions", "Resolve Contradictions"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pillarllmcall",
            name="result_data",
            field=models.JSONField(
                blank=True, help_text="Output data returned by the LLM", null=True
            ),
        ),
    ]
