# Generated by Django 5.2.7 on 2026-05-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pillars", "0012_remove_pillarllmcall_context_strategy"),
        ("projects", "__first__"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pillar",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pillars",
                to="projects.project",
            ),
        ),
    ]
