# Generated by Django 5.2.7 on 2026-05-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pillars", "0013_alter_pillar_project"),
        ("projects", "0004_remove_project_target_platform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pillar",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pillars",
                to="projects.project",
            ),
        ),
    ]
