# Generated by Django 5.2.7 on 2026-05-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pillars", "0014_alter_pillar_project"),
        ("projects", "0005_auto_20260510_1642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pillar",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pillars",
                to="projects.project",
            ),
        ),
    ]
