# Generated by Django 5.2 on 2025-05-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameDesignDescription",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Pillar",
            fields=[
                ("user_id", models.CharField(max_length=255)),
                (
                    "pillar_id",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
