# Generated by Django 5.2 on 2025-06-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodboardimage",
            name="image_url",
            field=models.CharField(max_length=512),
        ),
    ]
