# Generated by Django 5.2 on 2025-05-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pillar",
            name="user_id",
        ),
    ]
