# Generated by Django 5.2 on 2025-06-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pillar",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="pillar",
            name="pillar_id",
        ),
    ]
