# Generated by Django 5.2 on 2025-07-31 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0003_alter_gamedesigndescription_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moodboardimage",
            options={
                "verbose_name": "DEPRECATED: Legacy Moodboard Image",
                "verbose_name_plural": "DEPRECATED: Legacy Moodboard Images",
            },
        ),
        migrations.AlterModelOptions(
            name="moodboardsession",
            options={
                "verbose_name": "DEPRECATED: Legacy Moodboard Session",
                "verbose_name_plural": "DEPRECATED: Legacy Moodboard Sessions",
            },
        ),
        migrations.AlterField(
            model_name="gamedesigndescription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="game_designs",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
