# Generated by Django 5.2 on 2025-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pxchartedge",
            name="sourceHandle",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pxchartedge",
            name="targetHandle",
            field=models.CharField(default="", max_length=255),
        ),
    ]
