# Generated by Django 5.2 on 2025-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pxchartedge",
            name="unique_edge",
        ),
        migrations.RenameField(
            model_name="pxchartedge",
            old_name="destination",
            new_name="target",
        ),
        migrations.AddConstraint(
            model_name="pxchartedge",
            constraint=models.UniqueConstraint(
                fields=("px_chart", "source", "target"), name="unique_edge"
            ),
        ),
    ]
