# Generated by Django 5.2 on 2025-06-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pxchart",
            options={"verbose_name": "px chart", "verbose_name_plural": "px charts"},
        ),
        migrations.AlterModelOptions(
            name="pxchartedge",
            options={
                "verbose_name": "px chart edge",
                "verbose_name_plural": "px chart edges",
            },
        ),
        migrations.AlterModelOptions(
            name="pxchartnode",
            options={
                "verbose_name": "px chart node",
                "verbose_name_plural": "px chart nodes",
            },
        ),
        migrations.RemoveConstraint(
            model_name="pxchartedge",
            name="unique_edge",
        ),
        migrations.RenameField(
            model_name="pxchartedge",
            old_name="pxChart",
            new_name="px_chart",
        ),
        migrations.RenameField(
            model_name="pxchartnode",
            old_name="pxChart",
            new_name="px_chart",
        ),
        migrations.AddConstraint(
            model_name="pxchartedge",
            constraint=models.UniqueConstraint(
                fields=("px_chart", "source", "destination"), name="unique_edge"
            ),
        ),
    ]
