# Generated by Django 5.2 on 2025-07-13 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0002_pxchartedge_sourcehandle_pxchartedge_targethandle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pxchartedge",
            name="unique_edge",
        ),
        migrations.AddConstraint(
            model_name="pxchartedge",
            constraint=models.UniqueConstraint(
                fields=("px_chart", "source", "sourceHandle", "target", "targetHandle"),
                name="unique_edge",
            ),
        ),
    ]
