# Generated by Django 5.2 on 2025-07-28 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0003_remove_pxchartedge_unique_edge_and_more"),
        (
            "pxnodes",
            "0004_alter_pxcomponent_id_alter_pxcomponentdefinition_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PxChartNode",
            new_name="PxChartContainer",
        ),
        migrations.RenameModel(
            old_name="PxChartNodeLayout",
            new_name="PxChartContainerLayout",
        ),
        migrations.AlterModelOptions(
            name="pxchartcontainer",
            options={
                "verbose_name": "px chart container",
                "verbose_name_plural": "px chart containers",
            },
        ),
    ]
