# Generated by Django 5.2 on 2025-07-07 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0003_pxchartedge_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pxchartnode",
            name="position_x",
        ),
        migrations.RemoveField(
            model_name="pxchartnode",
            name="position_y",
        ),
        migrations.CreateModel(
            name="PxChartNodeLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("height", models.FloatField(default=0)),
                ("width", models.FloatField(default=0)),
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout",
                        to="pxcharts.pxchartnode",
                    ),
                ),
            ],
        ),
    ]
