# Generated by Django 5.2 on 2025-07-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0004_rename_pxchartnode_pxchartcontainer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pxchartcontainerlayout",
            old_name="node",
            new_name="container",
        ),
        migrations.AlterField(
            model_name="pxchartcontainer",
            name="px_chart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="containers",
                to="pxcharts.pxchart",
            ),
        ),
    ]
