# Generated by Django 5.2 on 2025-07-08 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0004_remove_pxchartnode_position_x_and_more"),
        ("pxnodes", "0002_pxcomponentdefinition_pxcomponent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pxchartnode",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chartnodes",
                to="pxnodes.pxnode",
            ),
        ),
    ]
