# Generated by Django 5.2 on 2025-07-08 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0005_alter_pxchartnode_content"),
        ("pxnodes", "0002_pxcomponentdefinition_pxcomponent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pxchartnode",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pxnodes.pxnode",
            ),
        ),
    ]
