# Generated by Django 5.2 on 2025-07-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0005_rename_node_pxchartcontainerlayout_container_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pxchartedge",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_edges",
                to="pxcharts.pxchartcontainer",
            ),
        ),
        migrations.AlterField(
            model_name="pxchartedge",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_edges",
                to="pxcharts.pxchartcontainer",
            ),
        ),
    ]
