# Generated by Django 5.2 on 2025-07-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0006_alter_pxchartedge_source_alter_pxchartedge_target"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pxchartcontainerlayout",
            options={
                "verbose_name": "px chart container layout",
                "verbose_name_plural": "px chart container layouts",
            },
        ),
    ]
