# Generated by Django 5.2 on 2025-08-09 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0007_alter_pxchartcontainerlayout_options"),
        (
            "pxnodes",
            "0004_alter_pxcomponent_id_alter_pxcomponentdefinition_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pxchart",
            name="associatedNode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charts",
                to="pxnodes.pxnode",
            ),
        ),
    ]
