# Generated by Django 5.2 on 2025-08-01 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pxcharts", "0007_alter_pxchartcontainerlayout_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pxchartcontainer",
            name="content",
        ),
        migrations.AddField(
            model_name="pxchartcontainer",
            name="content_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pxchartcontainer",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
    ]
