# Generated by Django 5.2.7 on 2026-03-14 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0008_pxchart_associatednode"),
        ("pxnodes", "0005_pxkeydefinition_pxkeyassignment_pxlockdefinition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PxLockAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pxnodes.pxlockdefinition",
                    ),
                ),
                (
                    "edge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pxcharts.pxchartedge",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "px_chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locks",
                        to="pxcharts.pxchart",
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "id")},
            },
        ),
    ]
