# Generated by Django 5.2.7 on 2026-03-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0009_pxlockassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="pxlockassignment",
            name="count",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
