# Generated by Django 5.2.7 on 2026-05-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0011_pxchartpathsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pxchartpathsettings",
            name="px_chart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="pxcharts.pxchart",
            ),
        ),
    ]
