# Generated by Django 5.2.7 on 2026-05-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_auto_20260510_1642"),
        ("pxcharts", "0012_alter_pxchart_project_alter_pxchartcontainer_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pxchart",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pxcharts",
                to="projects.project",
            ),
        ),
    ]
