# Generated by Django 5.2.7 on 2026-05-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0012_alter_pxchartpathsettings_px_chart"),
        ("pxcharts", "0013_alter_pxchart_project"),
    ]

    operations = []
