# Generated by Django 5.2.7 on 2026-05-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pxcharts", "0014_merge_20260513_1425"),
    ]

    operations = [
        migrations.AddField(
            model_name="pxchartedge",
            name="bidirectional",
            field=models.BooleanField(default=False),
        ),
    ]
