# Generated by Django 5.2.7 on 2026-06-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackendSessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("entries", models.JSONField(blank=True, default=list)),
                ("event_count", models.PositiveIntegerField(default=0)),
                (
                    "highest_level",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("first_entry_at", models.DateTimeField(blank=True, null=True)),
                ("last_entry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
