# Generated by Django 5.2 on 2025-07-20 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Moodboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Untitled Moodboard", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the moodboard concept",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gaming", "Gaming"),
                            ("ui_ux", "UI/UX Design"),
                            ("concept_art", "Concept Art"),
                            ("character_design", "Character Design"),
                            ("environment", "Environment"),
                            ("product_design", "Product Design"),
                            ("branding", "Branding"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for easier searching",
                        max_length=500,
                    ),
                ),
                (
                    "color_palette",
                    models.JSONField(
                        blank=True,
                        help_text="Saved color palette as JSON array",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Make this moodboard publicly viewable"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moodboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MoodboardImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        help_text="URL or path to the image", max_length=1000
                    ),
                ),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True,
                        help_text="URL or path to thumbnail",
                        max_length=1000,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "prompt",
                    models.TextField(
                        blank=True, help_text="Prompt used to generate this image"
                    ),
                ),
                (
                    "generation_params",
                    models.JSONField(
                        blank=True,
                        help_text="Parameters used for AI generation",
                        null=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ai_generated", "AI Generated"),
                            ("uploaded", "User Uploaded"),
                            ("url_import", "Imported from URL"),
                            ("stock", "Stock Image"),
                        ],
                        default="ai_generated",
                        max_length=20,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=500)),
                ("is_selected", models.BooleanField(default=False)),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in the moodboard"
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moodboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="moodboards.moodboard",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MoodboardComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moodboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="moodboards.moodboard",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="moodboards.moodboardcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="moodboards.moodboardimage",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MoodboardShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("comment", "View and Comment"),
                            ("edit", "View and Edit"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "moodboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moodboards.moodboard",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="moodboard",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_moodboards",
                through="moodboards.MoodboardShare",
                through_fields=("moodboard", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MoodboardTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("starter", "Starter Template"),
                            ("category", "Category Template"),
                            ("style", "Style Template"),
                            ("mood", "Mood Template"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gaming", "Gaming"),
                            ("ui_ux", "UI/UX Design"),
                            ("concept_art", "Concept Art"),
                            ("character_design", "Character Design"),
                            ("environment", "Environment"),
                            ("product_design", "Product Design"),
                            ("branding", "Branding"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "default_prompts",
                    models.JSONField(help_text="Default prompts for this template"),
                ),
                ("default_tags", models.CharField(blank=True, max_length=500)),
                ("default_color_palette", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_count", "title"],
            },
        ),
        migrations.AddIndex(
            model_name="moodboardimage",
            index=models.Index(
                fields=["moodboard", "is_selected"],
                name="moodboards__moodboa_c1429f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moodboardimage",
            index=models.Index(fields=["source"], name="moodboards__source_51073f_idx"),
        ),
        migrations.AddIndex(
            model_name="moodboardimage",
            index=models.Index(
                fields=["created_at"], name="moodboards__created_f8563e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moodboardcomment",
            index=models.Index(
                fields=["moodboard", "created_at"],
                name="moodboards__moodboa_7f7191_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moodboardcomment",
            index=models.Index(fields=["user"], name="moodboards__user_id_f497c6_idx"),
        ),
        migrations.AddIndex(
            model_name="moodboardshare",
            index=models.Index(
                fields=["moodboard", "permission"],
                name="moodboards__moodboa_bf2d03_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moodboardshare",
            unique_together={("moodboard", "user")},
        ),
        migrations.AddIndex(
            model_name="moodboard",
            index=models.Index(
                fields=["user", "status"], name="moodboards__user_id_834bf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moodboard",
            index=models.Index(
                fields=["category"], name="moodboards__categor_4a2528_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moodboard",
            index=models.Index(
                fields=["created_at"], name="moodboards__created_7b28e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moodboard",
            index=models.Index(
                fields=["is_public"], name="moodboards__is_publ_64d432_idx"
            ),
        ),
    ]
