# Generated by Django 5.2 on 2025-07-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moodboards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodboardshare",
            name="permission",
            field=models.CharField(
                choices=[("view", "View Only"), ("edit", "View and Edit")],
                default="view",
                max_length=20,
            ),
        ),
    ]
