# Generated by Django 5.2 on 2025-07-27 22:58

from django.db import migrations


def convert_comment_to_view(apps, schema_editor):
    """Convert any 'comment' permissions to 'view' permissions"""
    MoodboardShare = apps.get_model("moodboards", "MoodboardShare")
    MoodboardShare.objects.filter(permission="comment").update(permission="view")


def reverse_convert_comment_to_view(apps, schema_editor):
    """Reverse operation - convert 'view' back to 'comment' (not perfect but safe)"""
    # We can't perfectly reverse this since we don't know which 'view' were originally 'comment'
    # So we'll just leave them as 'view' - this is a safe operation
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("moodboards", "0002_update_permissions"),
    ]

    operations = [
        migrations.RunPython(convert_comment_to_view, reverse_convert_comment_to_view),
    ]
