# Generated by Django 5.2 on 2025-11-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moodboards", "0005_moodboard_canvas_background_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodboard",
            name="canvas_drawing_layer",
            field=models.CharField(
                blank=True,
                help_text="Drawing layer image (base64 or URL)",
                max_length=1000,
            ),
        ),
    ]
