# Generated by Django 5.2 on 2025-11-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moodboards", "0006_moodboard_canvas_drawing_layer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodboard",
            name="canvas_drawing_layer",
            field=models.TextField(
                blank=True, help_text="Drawing layer image (base64 or URL)"
            ),
        ),
    ]
