name: CI Pipeline Backend # Lint and Type Check Python Code (with Reviewdog)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort mypy

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1

      # Run Black
      - name: Run Black with reviewdog
        run: |
          black --check --diff . | reviewdog -f=diff -name="black" -reporter=github-pr-review -fail-on-error=false

      # Run isort
      - name: Run isort with reviewdog
        run: |
          isort --check-only --diff . | reviewdog -f=diff -name="isort" -reporter=github-pr-review -fail-on-error=false

      # Run Flake8
      - name: Run flake8 with reviewdog
        run: |
          flake8 . | reviewdog -f=flake8 -name="flake8" -reporter=github-pr-review -fail-on-error=false

      # Run mypy
      - name: Run mypy with reviewdog
        run: |
          mypy . | reviewdog -f=pep8 -name="mypy" -reporter=github-pr-review -fail-on-error=false
