# Generated by Django 5.2 on 2025-10-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerExpectationsAbsa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unnamed_0",
                    models.IntegerField(blank=True, db_column="Unnamed: 0", null=True),
                ),
                ("appid", models.IntegerField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("release_date", models.TextField(blank=True, null=True)),
                ("required_age", models.IntegerField(blank=True, null=True)),
                ("price", models.TextField(blank=True, null=True)),
                ("dlc_count", models.IntegerField(blank=True, null=True)),
                ("categories", models.TextField(blank=True, null=True)),
                ("genres", models.TextField(blank=True, null=True)),
                ("user_score", models.IntegerField(blank=True, null=True)),
                ("positive", models.IntegerField(blank=True, null=True)),
                ("negative", models.IntegerField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                ("review_text", models.TextField(blank=True, null=True)),
                ("explicit_expectations", models.TextField(blank=True, null=True)),
                ("has_explicit", models.TextField(blank=True, null=True)),
                ("expectations", models.TextField(blank=True, null=True)),
                (
                    "absa_expectations",
                    models.TextField(
                        blank=True, db_column="ABSA_expectations", null=True
                    ),
                ),
                ("dominant_aspect", models.TextField(blank=True, null=True)),
                ("dominant_sentiment", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "player_expectations_absa",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PlayerExpectationsConfusions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField(blank=True, null=True)),
                ("sentence", models.TextField(blank=True, null=True)),
                ("model_aspect", models.TextField(blank=True, null=True)),
                ("gpt_aspect", models.TextField(blank=True, null=True)),
                ("agreement", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "player_expectations_confusions",
                "managed": True,
            },
        ),
    ]
